### ISSUE TITLE
Support for Profiles API

### ISSUE THREAD

**Issue by caseydierking** [PrimePenguin/SquareSpaceSharp#5]
Hi team,

I was wondering if you had any plans to integrate the Profiles API into this library.
https://developers.squarespace.com/commerce-apis/profiles-overview

Everything else has been working great but would be so handy to have the profiles section integrated as well. 

Do you have plans for this?
Thanks,

**Comment by ajayak** [comment]
Hi @caseydierking, we don't have plans to implement Profile and Transactions API into this library anytime soon.
But a PR would be appreciated 😺

**Comment by caseydierking** [comment]
Ok. I'll implement it and submit a pull request shortly.
